# Generated by Django 5.2.5 on 2025-09-07 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefield',
            options={'ordering': ['tab', 'order', 'name']},
        ),
        migrations.CreateModel(
            name='ServiceTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='api.service')),
            ],
            options={
                'db_table': 'service_tabs',
                'ordering': ['order', 'name'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.AddField(
            model_name='servicefield',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.servicetab'),
        ),
    ]
