# Generated by Django 5.2.6 on 2025-09-08 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresettoken_phoneverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
