# Generated by Django 5.2.6 on 2025-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workshop',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='machines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workshop',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workshop',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workshop',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
