# Generated by Django 5.2.6 on 2025-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workshop_capabilities_workshop_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='documentation_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='supports_documentation',
            field=models.BooleanField(default=False),
        ),
    ]
