# Generated by Django 5.2.5 on 2025-09-11 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_documentation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCaptchaAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('success', models.BooleanField()),
                ('response_raw', models.JSONField(blank=True, null=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hcaptcha_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcaptcha_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='hcaptcha_at_created_bf794a_idx'), models.Index(fields=['ip'], name='hcaptcha_at_ip_c60e73_idx'), models.Index(fields=['success'], name='hcaptcha_at_success_d9132e_idx'), models.Index(fields=['endpoint'], name='hcaptcha_at_endpoin_ee5c5c_idx')],
            },
        ),
    ]
