# Generated by Django 5.2.5 on 2025-09-11 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_hcaptcha_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFileType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('image', 'تصویر'), ('document', 'سند'), ('cad_3d', 'فایل سه بعدی'), ('drawing', 'نقشه'), ('other', 'سایر')], max_length=20)),
                ('extensions', models.JSONField(default=list)),
                ('mime_types', models.JSONField(default=list)),
                ('max_size_mb', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ticket_file_types',
            },
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='attachment_type',
            field=models.CharField(choices=[('initial', 'فایل اولیه'), ('revision', 'بازبینی'), ('final', 'فایل نهایی'), ('reference', 'مرجع'), ('other', 'سایر')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('closed', 'بسته'), ('waiting_response', 'در انتظار پاسخ'), ('quarantined', 'قرنطینه شده'), ('escalated', 'ارجاع شده')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentFilterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('phone', 'شماره تلفن'), ('email', 'ایمیل'), ('url', 'لینک'), ('social_id', 'آیدی شبکه اجتماعی'), ('contact_invitation', 'دعوت به ارتباط خارجی'), ('other', 'سایر')], max_length=20)),
                ('detected_content', models.TextField()),
                ('original_content', models.TextField()),
                ('action_taken', models.CharField(choices=[('blocked', 'مسدود شده'), ('quarantined', 'قرنطینه شده'), ('warning', 'هشدار'), ('allowed', 'مجاز')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_violations', to='api.ticketmessage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_violations', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_violations', to='api.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_filter_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.ticketfiletype'),
        ),
    ]
