# Generated by Django 5.2.5 on 2025-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticketfiletype_alter_ticketattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_tabs',
            field=models.BooleanField(default=False),
        ),
    ]
