# Generated by Django 5.2.5 on 2025-09-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_turnstile_attempt'),
        ('api', '0011_turnstileattempt_delete_hcaptchaattempt_and_more'),
    ]

    operations = [
    ]
