# Generated by Django 5.2.5 on 2025-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20250920_1544'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='turnstileattempt',
            new_name='turnstile_a_created_9679d0_idx',
            old_name='turnstile_at_created_idx',
        ),
        migrations.RenameIndex(
            model_name='turnstileattempt',
            new_name='turnstile_a_ip_8d290d_idx',
            old_name='turnstile_at_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='turnstileattempt',
            new_name='turnstile_a_success_45d9bf_idx',
            old_name='turnstile_at_success_idx',
        ),
        migrations.RenameIndex(
            model_name='turnstileattempt',
            new_name='turnstile_a_endpoin_c87265_idx',
            old_name='turnstile_at_endpoint_idx',
        ),
        migrations.AlterField(
            model_name='turnstileattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
