# Generated by Django 5.2.5 on 2025-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_blogpost_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnstileattempt',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
