# Generated by Django 5.2.5 on 2025-09-29 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_turnstileattempt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponsePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('keyword_response', 'پاسخ بر اساس کلمه کلیدی'), ('domain_response', 'پاسخ بر اساس حوزه'), ('context_response', 'پاسخ بر اساس زمینه'), ('user_type_response', 'پاسخ بر اساس نوع کاربر')], max_length=30)),
                ('trigger_keywords', models.JSONField(default=list, help_text='کلمات کلیدی محرک')),
                ('trigger_domains', models.JSONField(default=list, help_text='حوزه\u200cهای محرک')),
                ('trigger_context', models.JSONField(default=dict, help_text='زمینه محرک')),
                ('response_template', models.TextField(help_text='قالب پاسخ')),
                ('response_examples', models.JSONField(default=list, help_text='نمونه\u200cهای پاسخ')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_satisfaction', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الگوی پاسخ هوش مصنوعی',
                'verbose_name_plural': 'الگوهای پاسخ هوش مصنوعی',
                'ordering': ['-success_rate', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_input', models.TextField(help_text='ورودی کاربر')),
                ('ai_response', models.TextField(help_text='پاسخ هوش مصنوعی')),
                ('interaction_type', models.CharField(choices=[('question', 'سوال'), ('feedback', 'بازخورد'), ('complaint', 'شکایت'), ('compliment', 'تعریف'), ('suggestion', 'پیشنهاد')], default='question', max_length=20)),
                ('user_context', models.JSONField(default=dict, help_text='زمینه کاربر')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('response_tokens', models.IntegerField(default=0)),
                ('user_satisfaction', models.CharField(blank=True, choices=[('very_dissatisfied', 'خیلی ناراضی'), ('dissatisfied', 'ناراضی'), ('neutral', 'خنثی'), ('satisfied', 'راضی'), ('very_satisfied', 'خیلی راضی')], max_length=20, null=True)),
                ('user_feedback_text', models.TextField(blank=True, null=True)),
                ('response_helpful', models.BooleanField(blank=True, null=True)),
                ('response_accurate', models.BooleanField(blank=True, null=True)),
                ('keywords_detected', models.JSONField(default=list, help_text='کلمات کلیدی تشخیص داده شده')),
                ('domain_identified', models.CharField(blank=True, help_text='حوزه شناسایی شده', max_length=50)),
                ('response_quality_score', models.FloatField(default=0.0, help_text='امتیاز کیفیت پاسخ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ تعامل هوش مصنوعی',
                'verbose_name_plural': 'لاگ\u200cهای تعامل هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
    ]
