# Generated by Django 5.2.5 on 2025-10-08 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_ai_learning_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='عنوان محتوا', max_length=200)),
                ('slug', models.SlugField(help_text='آدرس URL محتوا', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='خلاصه محتوا', max_length=500)),
                ('content', models.TextField(help_text='محتوای کامل')),
                ('content_type', models.CharField(choices=[('article', 'مقاله'), ('book', 'کتاب'), ('software', 'نرم\u200cافزار کاربردی'), ('video', 'ویدیو')], default='article', max_length=20)),
                ('category', models.CharField(choices=[('mechatronics', 'مکاترونیک'), ('mechanical', 'مهندسی مکانیک'), ('electronics', 'مهندسی الکترونیک'), ('computer', 'مهندسی کامپیوتر'), ('metaverse', 'متاورس'), ('ai', 'هوش مصنوعی'), ('simulation', 'شبیه\u200cسازی'), ('design', 'طراحی'), ('manufacturing', 'ساخت و تولید'), ('general', 'عمومی')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20)),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات متا برای SEO', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='کلمات کلیدی برای SEO', max_length=200)),
                ('featured_image', models.URLField(blank=True, help_text='تصویر شاخص مقاله', null=True)),
                ('source_url', models.URLField(blank=True, help_text='لینک منبع اصلی', null=True)),
                ('source_name', models.CharField(blank=True, help_text='نام منبع', max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('download_url', models.URLField(blank=True, help_text='لینک دانلود (برای نرم\u200cافزار و کتاب)', null=True)),
                ('video_url', models.URLField(blank=True, help_text='لینک ویدیو (برای محتوای ویدیویی)', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='حجم فایل (برای دانلود)', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='مدت زمان ویدیو (ثانیه)', null=True)),
                ('file_name', models.CharField(blank=True, help_text='نام فایل اصلی', max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='نوع فایل (pdf, docx, etc)', max_length=50)),
                ('file_path', models.CharField(blank=True, help_text='مسیر فایل در storage', max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='آیا فایل عمومی است یا نیاز به احراز هویت دارد')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='تعداد دانلودها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محتوا علمی',
                'verbose_name_plural': 'مطالب علمی',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
