# Generated by Django 5.2.5 on 2025-10-20 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_scientificcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('material', 'پرداخت متریال'), ('project_advance', 'پیش پرداخت پروژه'), ('project_final', 'تسویه حساب پروژه'), ('shipping', 'هزینه ارسال')], default='project_advance', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'ثبت شده'), ('admin_approved', 'تایید ادمین'), ('proposals_received', 'دریافت پیشنهادات'), ('proposal_accepted', 'پیشنهاد پذیرفته شده'), ('material_paid', 'متریال پرداخت شده'), ('project_paid', 'پروژه پرداخت شده'), ('in_progress', 'در حال انجام'), ('documentation_submitted', 'مستندات ارسال شده'), ('final_payment_pending', 'در انتظار تسویه حساب'), ('shipping', 'در حال ارسال'), ('delivered', 'تحویل به مشتری'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='مبلغ به تومان', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('refunded', 'بازگردانده شده')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_cost', models.DecimalField(decimal_places=0, help_text='هزینه برآورد شده متریال به تومان', max_digits=12)),
                ('description', models.TextField(help_text='توضیحات متریال و هزینه')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_estimate', to='api.order')),
            ],
            options={
                'db_table': 'material_estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'ثبت شده'), ('admin_approved', 'تایید ادمین'), ('proposals_received', 'دریافت پیشنهادات'), ('proposal_accepted', 'پیشنهاد پذیرفته شده'), ('material_paid', 'متریال پرداخت شده'), ('project_paid', 'پروژه پرداخت شده'), ('in_progress', 'در حال انجام'), ('documentation_submitted', 'مستندات ارسال شده'), ('final_payment_pending', 'در انتظار تسویه حساب'), ('shipping', 'در حال ارسال'), ('delivered', 'تحویل به مشتری'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='توضیحات تغییر وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت به تومان', max_digits=12)),
                ('delivery_days', models.PositiveIntegerField(help_text='تعداد روز تحویل')),
                ('description', models.TextField(help_text='توضیحات انجام پروژه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.order')),
            ],
            options={
                'db_table': 'order_proposals',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'contractor')},
            },
        ),
    ]
