# Generated by Django 5.2.5 on 2025-10-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_payment_options_remove_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='webhook_nonce',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='materialestimate',
            index=models.Index(fields=['order'], name='idx_material_order'),
        ),
        migrations.AddIndex(
            model_name='materialestimate',
            index=models.Index(fields=['is_paid'], name='idx_material_is_paid'),
        ),
        migrations.AddIndex(
            model_name='orderproposal',
            index=models.Index(fields=['order'], name='idx_proposal_order'),
        ),
        migrations.AddIndex(
            model_name='orderproposal',
            index=models.Index(fields=['status'], name='idx_proposal_status'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['order'], name='idx_orderstatus_order'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['status'], name='idx_orderstatus_status'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['created_at'], name='idx_orderstatus_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='idx_payment_order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='idx_payment_type'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='idx_payment_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_transaction_id'], name='idx_payment_gtid'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['webhook_nonce'], name='idx_payment_nonce'),
        ),
    ]
