# Generated by Django 5.2.5 on 2025-10-22 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_payment_webhook_nonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEstimation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(help_text='نام متریال', max_length=200)),
                ('material_type', models.CharField(help_text='نوع متریال', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='مقدار', max_digits=10)),
                ('unit', models.CharField(help_text='واحد اندازه\u200cگیری', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='قیمت واحد', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='قیمت کل', max_digits=12)),
                ('supplier_name', models.CharField(blank=True, help_text='نام تامین کننده', max_length=200)),
                ('supplier_contact', models.CharField(blank=True, help_text='اطلاعات تماس تامین کننده', max_length=200)),
                ('specifications', models.TextField(blank=True, help_text='مشخصات فنی')),
                ('delivery_time', models.PositiveIntegerField(help_text='زمان تحویل (روز)')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cها')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('revised', 'بازنگری شده')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_material_estimations', to=settings.AUTH_USER_MODEL)),
                ('estimator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_estimations', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_estimations', to='api.orderitem')),
            ],
            options={
                'verbose_name': 'برآورد متریال',
                'verbose_name_plural': 'برآوردهای متریال',
                'ordering': ['-created_at'],
            },
        ),
    ]
