# Generated by Django 5.2.5 on 2025-10-27 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_servicefield_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='مسیر فایل در سیستم', max_length=500)),
                ('file_name', models.CharField(help_text='نام فایل', max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='اندازه فایل به بایت')),
                ('content_type', models.CharField(default='application/octet-stream', help_text='نوع محتوا', max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0, help_text='تعداد دانلود')),
                ('last_download', models.DateTimeField(blank=True, help_text='آخرین زمان دانلود', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='فعال بودن لینک دانلود')),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاریخ انقضا', null=True)),
                ('description', models.TextField(blank=True, help_text='توضیحات فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_files', to='api.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل تحویلی',
                'verbose_name_plural': 'فایل\u200cهای تحویلی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='api_deliver_order_i_63b984_idx'), models.Index(fields=['upload_date'], name='api_deliver_upload__4e8af7_idx')],
            },
        ),
    ]
