# Generated by Django 5.2.5 on 2025-10-27 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_deliveryfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(help_text='عنوان شغل (مثلاً: تراشکار، برنامه\u200cنویس)', max_length=200)),
                ('experience_years', models.PositiveIntegerField(help_text='سال\u200cهای تجربه')),
                ('education', models.CharField(choices=[('no_degree', 'بدون مدرک'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], help_text='مدرک تحصیلی', max_length=20)),
                ('cv_text', models.TextField(help_text='رزومه کامل (تخصص\u200cها و توانایی\u200cها)')),
                ('skills', models.JSONField(blank=True, default=list, help_text='لیست مهارت\u200cها')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل')),
                ('phone_alt', models.CharField(blank=True, help_text='شماره تماس اضافی', max_length=17)),
                ('emergency_contact', models.CharField(blank=True, help_text='مخاطب اضطراری', max_length=200)),
                ('emergency_phone', models.CharField(blank=True, help_text='تلفن اضطراری', max_length=17)),
                ('is_active', models.BooleanField(default=True, help_text='فعال بودن پروفایل')),
                ('is_available', models.BooleanField(default=True, help_text='در دسترس برای استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seekers', to='api.scope')),
                ('services', models.ManyToManyField(blank=True, help_text='خدمات قابل ارائه', related_name='job_seekers', to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جویای کار',
                'verbose_name_plural': 'جویای\u200cکارها',
                'db_table': 'job_seekers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0, help_text='امتیاز تطابق (0-100)')),
                ('match_reason', models.TextField(blank=True, help_text='دلیل پیشنهاد این نیرو')),
                ('status', models.CharField(choices=[('suggested', 'پیشنهاد شده'), ('accepted_contractor', 'تایید شده توسط کارفرما'), ('accepted_seeker', 'تایید شده توسط کارجو'), ('rejected', 'رد شده'), ('sent_for_test', 'ارسال برای تست'), ('test_passed', 'تست موفق'), ('test_failed', 'تست ناموفق'), ('contract_signed', 'قرارداد امضا شده')], default='suggested', max_length=30)),
                ('test_start_date', models.DateTimeField(blank=True, help_text='شروع تست', null=True)),
                ('test_end_date', models.DateTimeField(blank=True, help_text='پایان تست', null=True)),
                ('test_result', models.TextField(blank=True, help_text='نتیجه تست')),
                ('test_notes', models.TextField(blank=True, help_text='یادداشت\u200cهای تست')),
                ('contractor_feedback', models.TextField(blank=True, help_text='نظر کارفرما')),
                ('seeker_feedback', models.TextField(blank=True, help_text='نظر کارجو')),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_matches', to=settings.AUTH_USER_MODEL)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.jobseeker')),
            ],
            options={
                'verbose_name': 'تطابق شغل',
                'verbose_name_plural': 'تطابق\u200cهای شغل',
                'db_table': 'job_matches',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_job_title', models.CharField(help_text='عنوان شغل مورد نظر', max_length=200)),
                ('required_skills', models.JSONField(default=list, help_text='مهارت\u200cهای مورد نیاز')),
                ('min_experience', models.PositiveIntegerField(default=0, help_text='حداقل تجربه (سال)')),
                ('preferred_education', models.CharField(blank=True, choices=[('no_degree', 'بدون مدرک'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], help_text='مدرک تحصیلی ترجیحی', max_length=20)),
                ('offered_salary', models.DecimalField(blank=True, decimal_places=0, help_text='حقوق پیشنهادی (تومان)', max_digits=10, null=True)),
                ('work_hours', models.CharField(blank=True, help_text='ساعت کار', max_length=100)),
                ('work_location', models.CharField(help_text='محل کار', max_length=200)),
                ('work_type', models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('contract', 'پیمانی'), ('hourly', 'ساعتی')], default='full_time', help_text='نوع کار', max_length=50)),
                ('description', models.TextField(help_text='شرح کامل نیاز')),
                ('requirements', models.TextField(blank=True, help_text='نیازمندی\u200cهای اضافی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('in_process', 'در حال جذب نیرو'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_requests', to=settings.AUTH_USER_MODEL)),
                ('required_services', models.ManyToManyField(blank=True, help_text='خدمات مورد نیاز', related_name='work_requests', to='api.service')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('service_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='api.scope')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_requests', to='api.workshop')),
            ],
            options={
                'verbose_name': 'درخواست نیروی کار',
                'verbose_name_plural': 'درخواست\u200cهای نیروی کار',
                'db_table': 'work_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(blank=True, help_text='شماره قرارداد', max_length=50, unique=True)),
                ('start_date', models.DateTimeField(help_text='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, help_text='تاریخ پایان', null=True)),
                ('salary_amount', models.DecimalField(decimal_places=0, help_text='مبلغ حقوق (تومان)', max_digits=10)),
                ('salary_frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهیانه'), ('hourly', 'ساعتی'), ('project_based', 'پروژه\u200cای')], default='monthly', help_text='فرکانس پرداخت', max_length=20)),
                ('work_hours', models.CharField(help_text='ساعت کار', max_length=100)),
                ('work_location', models.CharField(help_text='محل کار', max_length=200)),
                ('responsibilities', models.TextField(help_text='وظایف و مسئولیت\u200cها')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_signer', 'در انتظار امضا'), ('pending_seeker', 'در انتظار امضای کارجو'), ('active', 'فعال'), ('completed', 'تکمیل شده'), ('terminated', 'خاتمه یافته')], default='draft', max_length=20)),
                ('contractor_signed', models.BooleanField(default=False)),
                ('contractor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('seeker_signed', models.BooleanField(default=False)),
                ('seeker_signed_at', models.DateTimeField(blank=True, null=True)),
                ('contract_file_path', models.CharField(blank=True, help_text='مسیر فایل قرارداد', max_length=500)),
                ('termination_reason', models.TextField(blank=True, help_text='دلیل خاتمه')),
                ('termination_date', models.DateTimeField(blank=True, help_text='تاریخ خاتمه', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='try_created_contracts', to=settings.AUTH_USER_MODEL)),
                ('job_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='api.jobmatch')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.jobseeker')),
                ('termination_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_contracts', to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.workrequest')),
            ],
            options={
                'verbose_name': 'قرارداد کاری',
                'verbose_name_plural': 'قراردادهای کاری',
                'db_table': 'work_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='work_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.workrequest'),
        ),
        migrations.AddIndex(
            model_name='jobseeker',
            index=models.Index(fields=['is_active', 'is_available'], name='job_seekers_is_acti_8fdd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseeker',
            index=models.Index(fields=['job_title'], name='job_seekers_job_tit_4c5785_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['status'], name='work_reques_status_daceab_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['created_at'], name='work_reques_created_85ea15_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['contractor'], name='work_reques_contrac_200924_idx'),
        ),
        migrations.AddIndex(
            model_name='workcontract',
            index=models.Index(fields=['contract_number'], name='work_contra_contrac_456909_idx'),
        ),
        migrations.AddIndex(
            model_name='workcontract',
            index=models.Index(fields=['status'], name='work_contra_status_b003c2_idx'),
        ),
        migrations.AddIndex(
            model_name='workcontract',
            index=models.Index(fields=['contractor', 'job_seeker'], name='work_contra_contrac_c7af48_idx'),
        ),
        migrations.AddIndex(
            model_name='workcontract',
            index=models.Index(fields=['start_date', 'end_date'], name='work_contra_start_d_7587b3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['status'], name='job_matches_status_e4de12_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['match_score'], name='job_matches_match_s_c4667a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['work_request', 'job_seeker'], name='job_matches_work_re_dce4e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobmatch',
            unique_together={('work_request', 'job_seeker')},
        ),
    ]
