# Generated by Django migration
from django.db import migrations, models
from django.db import connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name=%s
            """, [table_name, column_name])
        else:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=? AND column_name=?
            """, [table_name, column_name])
        return cursor.fetchone() is not None


def migrate_forwards(apps, schema_editor):
    """Add fields only if they don't exist"""
    Workshop = apps.get_model('api', 'Workshop')
    table_name = Workshop._meta.db_table
    
    # Only add fields if they don't exist
    if not check_column_exists(table_name, 'is_approved'):
        schema_editor.add_field(
            Workshop,
            models.BooleanField(default=False, help_text='Whether the workshop is approved by admin'),
            name='is_approved'
        )
    
    if not check_column_exists(table_name, 'workshop_class'):
        schema_editor.add_field(
            Workshop,
            models.CharField(
                blank=True,
                choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')],
                help_text='Workshop classification (A, B, or C) - set by admin during approval',
                max_length=10
            ),
            name='workshop_class'
        )
    
    if not check_column_exists(table_name, 'documents'):
        schema_editor.add_field(
            Workshop,
            models.JSONField(
                blank=True,
                default=dict,
                help_text='Dictionary of document field keys to file URLs'
            ),
            name='documents'
        )
    
    if not check_column_exists(table_name, 'workers_count'):
        schema_editor.add_field(
            Workshop,
            models.IntegerField(
                blank=True,
                default=0,
                help_text='Number of formal workers in the workshop'
            ),
            name='workers_count'
        )


def migrate_backwards(apps, schema_editor):
    """Remove fields"""
    Workshop = apps.get_model('api', 'Workshop')
    try:
        schema_editor.remove_field(Workshop, 'is_approved')
    except Exception:
        pass
    try:
        schema_editor.remove_field(Workshop, 'workshop_class')
    except Exception:
        pass
    try:
        schema_editor.remove_field(Workshop, 'documents')
    except Exception:
        pass
    try:
        schema_editor.remove_field(Workshop, 'workers_count')
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_workshop_code'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrate_backwards),
    ]

