# Generated by Django 5.2.5 on 2025-11-11 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_workshop_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the workshop is approved by admin'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workers_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of formal workers'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], help_text='Workshop classification (A, B, or C) - set by admin during approval', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('customer', 'مشتری'), ('contractor', 'پیمانکار'), ('admin', 'مدیر'), ('support', 'پشتیبان'), ('specialist', 'نیروی متخصص')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(help_text='استان محل زندگی', max_length=100)),
                ('city', models.CharField(help_text='شهر', max_length=100)),
                ('address', models.TextField(help_text='آدرس محل زندگی')),
                ('birth_date', models.DateField(help_text='تاریخ تولد')),
                ('national_id', models.CharField(help_text='کد ملی (10 رقم)', max_length=10, unique=True)),
                ('education', models.CharField(choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor_student', 'دانشجو کارشناسی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], help_text='تحصیلات', max_length=30)),
                ('field_of_study', models.CharField(help_text='رشته تحصیلی', max_length=50)),
                ('skills', models.JSONField(blank=True, default=list, help_text='توانمندی\u200cها (حداکثر 10)')),
                ('work_experience', models.JSONField(blank=True, default=list, help_text='سابقه کار (حداکثر 10)')),
                ('resume_file', models.CharField(blank=True, help_text='مسیر فایل رزومه (private)', max_length=500)),
                ('description', models.CharField(blank=True, help_text='توضیحات (حداکثر 200 کاراکتر)', max_length=200)),
                ('is_approved', models.BooleanField(default=False, help_text='تایید شده توسط ادمین')),
                ('specialist_code', models.CharField(editable=False, help_text='کد اختصاصی', max_length=20, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_specialists', to=settings.AUTH_USER_MODEL)),
                ('specialization_services', models.ManyToManyField(blank=True, help_text='خدمات تخصصی', related_name='specialists', to='api.service')),
                ('specializations', models.ManyToManyField(blank=True, help_text='زمینه تخصصی', related_name='specialists', to='api.scope')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل نیروی متخصص',
                'verbose_name_plural': 'پروفایل\u200cهای نیروی متخصص',
                'db_table': 'specialist_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistHireRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='پیام درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('contacted', 'تماس برقرار شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='یادداشت ادمین')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('specialist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='api.specialistprofile')),
            ],
            options={
                'verbose_name': 'درخواست جذب نیروی متخصص',
                'verbose_name_plural': 'درخواست\u200cهای جذب نیروی متخصص',
                'db_table': 'specialist_hire_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['is_approved'], name='specialist__is_appr_1da8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['province', 'city'], name='specialist__provinc_b9aa8c_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['specialist_code'], name='specialist__special_781c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisthirerequest',
            index=models.Index(fields=['status'], name='specialist__status_5b685a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisthirerequest',
            index=models.Index(fields=['requester', 'specialist_profile'], name='specialist__request_223bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisthirerequest',
            index=models.Index(fields=['created_at'], name='specialist__created_668818_idx'),
        ),
    ]
