# Generated by Django 5.2.5 on 2025-11-18 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_workshop_documents_workshop_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the workshop is approved by admin'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workers_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of formal workers'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], help_text='Workshop classification (A, B, or C) - set by admin during approval', max_length=10),
        ),
        migrations.CreateModel(
            name='JobSeekerHireRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='پیام درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('contacted', 'تماس برقرار شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='یادداشت ادمین')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_job_seeker_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='api.jobseeker')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_hire_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست جذب نیروی کاریابی',
                'verbose_name_plural': 'درخواست\u200cهای جذب نیروی کاریابی',
                'db_table': 'job_seeker_hire_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='job_seeker__status_5ba133_idx'), models.Index(fields=['requester', 'job_seeker'], name='job_seeker__request_1a1531_idx'), models.Index(fields=['created_at'], name='job_seeker__created_02c979_idx')],
            },
        ),
    ]
