# Generated by Django 5.2.5 on 2025-12-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_specialistprofile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproposal',
            name='documentation_days',
            field=models.PositiveIntegerField(default=0, help_text='تعداد روز تحویل مستندات'),
        ),
        migrations.AddField(
            model_name='orderproposal',
            name='documentation_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='قیمت مستندات به تومان', max_digits=12),
        ),
    ]
