"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import logging
logger = logging.getLogger(__name__)

# Optional: load .env if python-dotenv is installed
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))
except Exception:
    pass

# Import file settings
try:
    from .file_settings import *
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY and DEBUG:  # Allow empty SECRET_KEY only in debug mode
    SECRET_KEY = 'development-secret-key-for-testing-only'
elif not SECRET_KEY and not DEBUG:
    raise ValueError("SECRET_KEY environment variable is required for production!")

# Hosts
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'testserver',
    'saydatech.ir',
    'www.saydatech.ir',
    os.getenv('ALLOWED_HOSTS', '')
]

# Frontend URL for password reset and other redirects
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://saydatech.ir')

# SMS Configuration
SMS_KEY = os.getenv('SMS_KEY', '')
SMS_SENDER = os.getenv('SMS_SENDER', 'SaydaTech')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'axes',  # For login lockout protection
    'captcha',  # For fallback captcha
    'csp',  # Content Security Policy
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.JWTAuthenticationMiddleware',  # Custom JWT middleware
    'axes.middleware.AxesMiddleware',  # Must be after AuthenticationMiddleware
    'csp.middleware.CSPMiddleware',  # Content Security Policy
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '..', 'templates'),  # Root templates directory
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# Use Postgres via env if provided, otherwise fallback to sqlite for dev
if os.getenv('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Use a runtime-writable directory to avoid permission issues in containers
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR.parent, 'staticfiles_runtime'))
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # Add frontend build directory for Liara (excluding PWA files)
    os.path.join(BASE_DIR, '..', 'dist'),
]

# Exclude PWA files from staticfiles collection
STATICFILES_IGNORE_PATTERNS = [
    'icons/',
    'screenshots/',
    'service-worker.js',
    'manifest.json',
    'web.config',
    'pwa-debug.js',
    'pwa-test.js',
    'mime-test.js',
]

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# CORS/CSRF for Vite dev server and mobile app
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://saydatech.ir',
    'http://www.saydatech.ir',
    'https://saydatech.ir',
    'https://www.saydatech.ir',
    # Mobile app origins (Expo/React Native)
    'exp://localhost:8081',
    'exp://192.168.*.*:8081',
    'exp://10.*.*.*:8081',
    'exp://172.*.*.*:8081',
]

# Allow mobile app user agents
CORS_ALLOW_ALL_ORIGINS = False  # Keep this False for security

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # Mobile app headers
    'x-app-version',
    'x-platform',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow credentials for CORS
CORS_ALLOW_CREDENTIALS = True


CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://saydatech.ir',
    'http://www.saydatech.ir',
    'https://saydatech.ir',
    'https://www.saydatech.ir',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'api.throttling.CustomAnonRateThrottle',
        'api.throttling.CustomUserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Reduced for security
        'user': '1000/hour',
        'burst': '60/minute',
        'sustained': '1000/hour',
        'upload': '10/hour',
        'login': '5/minute',  # Strict limit for login
        'register': '3/minute',  # Strict limit for registration
        'password_reset': '2/minute',  # Very strict for password reset
        'api': '500/hour'
    },
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
    'DEFAULT_VERSIONING_CLASS': 'api.versioning.CustomURLPathVersioning',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'DEFAULT_VERSION': 'v1'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'BLACKLIST_TOKEN_CHECKS': True,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Mech Craft Hub API',
    'DESCRIPTION': 'API documentation for the Mech Craft Hub backend',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Frontend URL for password reset links
if DEBUG:
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:8080')
else:
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://saydatech.ir')

# Email settings (for production)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # For production
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@mechcraft.com')

# Turnstile Configuration
TURNSTILE_SITE_KEY = os.environ.get("TURNSTILE_SITE_KEY")
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY")
TURNSTILE_VERIFY_URL = os.environ.get("TURNSTILE_VERIFY_URL", "https://challenges.cloudflare.com/turnstile/v0/siteverify")
TURNSTILE_FALLBACK_LOCAL = os.environ.get("TURNSTILE_FALLBACK_LOCAL", "False").lower() == "true"

# Security Settings - Quick Wins
# HTTPS and SSL Security (only for production with HTTPS)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

# HSTS (HTTP Strict Transport Security) - only for production
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Content Security
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'ALLOWALL'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Additional Security Headers
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Password Hashing (Argon2 - More secure than PBKDF2)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Content Security Policy (CSP) - New format for django-csp 4.0+
CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", "https://challenges.cloudflare.com"),
    'style-src': ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com"),
    'font-src': ("'self'", "https://fonts.gstatic.com"),
    'img-src': ("'self'", "data:", "https:"),
    'media-src': ("'self'", "https://storage.c2.liara.space", "https://storage.iran.liara.space", "https://*.liara.space"),
    'connect-src': ("'self'",),
    'object-src': ("'none'",),
    'base-uri': ("'self'",),
    'form-action': ("'self'",),
}

# Security Settings for Production (override development settings)
if not DEBUG:
    # Additional production security settings
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'ALLOWALL'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    # Development settings
    X_FRAME_OPTIONS = 'ALLOWALL'

# Cache Configuration (Redis for production, local memory for development)
if os.getenv('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Authentication backends
# NOTE: axes backend removed temporarily because it was blocking API logins.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# django-axes Configuration - Enhanced Security
# NOTE: Temporarily disabled because it was aggressively locking out API logins.
# DRF already has strict throttling on the login endpoint.
AXES_ENABLED = False  # Disable axes globally for now to restore login
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts (when re-enabled)
AXES_COOLOFF_TIME = 1  # 1 hour lockout
AXES_LOCKOUT_TEMPLATE = 'axes/lockout.html'
AXES_VERBOSE = True
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'user_agent']
AXES_RESET_ON_SUCCESS = True
AXES_DISABLE_ACCESS_LOG = False
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'
AXES_LOCKOUT_URL = '/locked/'
AXES_ENABLE_ADMIN = True
AXES_NEVER_LOCKOUT_WHITELIST = True
AXES_NEVER_LOCKOUT_GET = True
AXES_LOCKOUT_BY_COMBINATION_USER_AND_IP = True

# django-simple-captcha Configuration (for fallback)
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_LENGTH = 6
CAPTCHA_TIMEOUT = 5  # 5 minutes
CAPTCHA_IMAGE_SIZE = (120, 40)
CAPTCHA_FONT_SIZE = 22

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Sentry Configuration
SENTRY_DSN = os.getenv('SENTRY_DSN')
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', 'production')
SENTRY_RELEASE = os.getenv('SENTRY_RELEASE')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1'))

# AWS Configuration for S3 backups
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
S3_BACKUP_BUCKET = os.getenv('S3_BACKUP_BUCKET')

# File Storage Configuration for Scientific Content
FILE_STORAGE_TYPE = os.getenv('FILE_STORAGE_TYPE', 'liara')  # local, s3, liara
FILE_BUCKET_NAME = os.getenv('FILE_BUCKET_NAME', None) or os.getenv('BUCKET_NAME', 'resources')  # Liara bucket name
FILE_REGION = os.getenv('FILE_REGION', 'iran')
# Support both S3_ENDPOINT_URL and LIARA_ENDPOINT_URL for compatibility
S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL', None) or os.getenv('LIARA_ENDPOINT_URL', 'https://storage.iran.liara.space')
LIARA_ENDPOINT_URL = os.getenv('LIARA_ENDPOINT_URL', None) or S3_ENDPOINT_URL
FILE_PUBLIC_ACCESS = os.getenv('FILE_PUBLIC_ACCESS', 'True').lower() == 'true'
FILE_FALLBACK_TO_LOCAL = os.getenv('FILE_FALLBACK_TO_LOCAL', 'False').lower() == 'true'

# Liara Storage Credentials (for scientific content)
# Support both naming conventions for backward compatibility
LIARA_ACCESS_KEY = os.getenv('LIARA_ACCESS_KEY', None)
LIARA_SECRET_KEY = os.getenv('LIARA_SECRET_KEY', None)
LIARA_ACCESS_KEY_ID = os.getenv('LIARA_ACCESS_KEY_ID', None) or LIARA_ACCESS_KEY
LIARA_SECRET_ACCESS_KEY = os.getenv('LIARA_SECRET_ACCESS_KEY', None) or LIARA_SECRET_KEY

# ClamAV Configuration
CLAMAV_SOCKET = os.getenv('CLAMAV_SOCKET', '/var/run/clamav/clamd.ctl')
CLAMAV_ENABLED = os.getenv('CLAMAV_ENABLED', 'True').lower() == 'true'

# File Upload Security
MAX_FILE_SIZE = int(os.getenv('MAX_FILE_SIZE', '52428800'))  # 50MB
ALLOWED_FILE_TYPES = os.getenv('ALLOWED_FILE_TYPES', 'pdf,image,document,cad').split(',')

# Google Generative AI Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GEMINI_MODEL_NAME = os.getenv('GEMINI_MODEL_NAME', 'gemini-1.5-flash')

# SMS Configuration
SMS_KEY = os.getenv('SMS_KEY')
if not SMS_KEY:
    logger.error("SMS_KEY is not set in environment variables")
else:
    logger.info(f"SMS_KEY is configured: {SMS_KEY[:5]}...")  # Log first 5 chars for security

# SMS.ir sender line number
SMS_SENDER = os.getenv('SMS_SENDER')
if not SMS_SENDER:
    logger.warning("SMS_SENDER is not set in environment variables")

# Template IDs for verification, password reset, and notifications
SMS_TEMPLATE_ID_VERIFICATION = os.getenv('SMS_TEMPLATE_ID_VERIFICATION', None)
SMS_TEMPLATE_ID_PASSWORD_RESET = os.getenv('SMS_TEMPLATE_ID_PASSWORD_RESET', None)
SMS_TEMPLATE_ID_MANUFACTURING_ORDER = os.getenv('SMS_TEMPLATE_ID_MANUFACTURING_ORDER', None)
SMS_TEMPLATE_ID_APPROVE_WORKSHOP = os.getenv('SMS_TEMPLATE_ID_APPROVE_WORKSHOP', None)

# SMS API Configuration
SMS_API_TIMEOUT = int(os.getenv('SMS_API_TIMEOUT', '30'))  # 30 seconds default timeout
SMS_API_BASE_URL = os.getenv('SMS_API_BASE_URL', 'https://api.sms.ir/v1')

# Initialize Sentry
if SENTRY_DSN:
    from api.monitoring import init_sentry
    init_sentry()